print("Maked by Prince")
print("")
print("")
print("")

mathMarks = input("Enter Your Math Marks: ")
physicsMarks = input ("Enter Your Math Marks: ")
englishMarks = input ("Enter Your Physics Marks: ")
chemistryMarks = input ("Enter Your Chemistry Marks: ")
hindiMarks = input ("Enter Your Hindi Marks: ")

sum = int(mathMarks) + int(physicsMarks) + int(englishMarks) + int(chemistryMarks) + int(hindiMarks)
print("")
print("")
print("")
print('Total:',sum)
('Total:',sum*100)
    
print(',Your Percentage:',sum*100/500)
print("")
print("")
print("")
print("It,s Creater Was Aswvathama")
print ("subscribe now")
print ("THANKS FOR USING")